// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llvhlnafgblywiljvrsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsdmhsbmFmZ2JseXdpbGp2cnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTQxNzMsImV4cCI6MjA3MjYzMDE3M30.ivUAqL2XshHz3QSzdgjeXWGI4QgCJ6QldJKrLqd7-pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});