// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbxnvxvdfmxvaejegvvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhieG52eHZkZm14dmFlamVndnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDY0NTMsImV4cCI6MjA3MTUyMjQ1M30.0JiDWFou7zW9clV1NlXkR3DWhcEvZRWB3ASsvnM699U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});